{
 "title": "Solace broker",
 "description": "Analyse solace PubSub+ VPNs",
 "tags": [
  "solace",
  "broker"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(solace_vpn_connections, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Broker status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(solace_up{instance=\"$instance\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{instance_short}}"
    }
   ]
  },
  {
   "title": "mate link latency",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_system_mate_link_latency_avg_seconds{instance=\"$instance\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "disk latency",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_system_disk_latency_avg_seconds{instance=\"$instance\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "compute latency",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_system_compute_latency_avg_seconds{instance=\"$instance\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "Client connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(solace_vpn_connections{instance=\"$instance\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": " {{vpn_name}}@{{instance_short}}"
    }
   ]
  },
  {
   "title": "Msg Rate IN",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(solace_vpn_rx_msgs_rate{instance=\"$instance\",vpn_name!~\"^#.+\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}@{{instance_short}} IN"
    }
   ]
  },
  {
   "title": "Msg Rate OUT",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(solace_vpn_tx_msgs_rate{instance=\"$instance\",vpn_name!~\"^#.+\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}@{{instance_short}} OUT"
    }
   ]
  },
  {
   "title": "Date Rate IN",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(solace_vpn_rx_bytes_rate{instance=\"$instance\",vpn_name!~\"^#.+\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}@{{instance_short}} IN"
    }
   ]
  },
  {
   "title": "Date Rate OUT",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(solace_vpn_tx_bytes_rate{instance=\"$instance\",vpn_name!~\"^#.+\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}@{{instance_short}} OUT"
    }
   ]
  },
  {
   "title": "Ingress Discard IN",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(solace_vpn_rx_discarded_msgs_total{instance=\"$instance\",vpn_name!~\"^#.+\"}[5m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}@{{instance_short}} IN"
    }
   ]
  },
  {
   "title": "Egress Discard OUT",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(solace_vpn_tx_discarded_msgs_total{instance=\"$instance\",vpn_name!~\"^#.+\"}[5m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}@{{instance_short}} OUT"
    }
   ]
  },
  {
   "title": "Queue Spool Usage Bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(solace_queue_spool_usage_bytes{instance=\"$instance\",vpn_name!~\"^#.+\"}/1024.0/1024.0, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Queue Spool Usage Msgs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(solace_queue_spool_usage_msgs{instance=\"$instance\",vpn_name!~\"^#.+\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Transfer volume IN",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(solace_vpn_rx_bytes_total{instance=\"$instance\",vpn_name!~\"^#.+\"}[5m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}@{{instance_short}} IN"
    }
   ]
  },
  {
   "title": "Transfer volume OUT",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(solace_vpn_tx_bytes_total{instance=\"$instance\",vpn_name!~\"^#.+\"}[5m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}@{{instance_short}} OUT"
    }
   ]
  }
 ]
}